name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # يشغّل الـ Action فقط إذا صار push على فرع main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SSH command on Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/Chatbot-New
            git pull origin main
            sudo systemctl restart chromadb.service
            sudo systemctl restart backend.service
            sudo systemctl restart frontend.service

